version: 2.1

executors:
  linux-executor:
    docker:
      - image: ubuntu-2404:2024.11.1
    resource_class: small
    working_directory: ~/tau-lang

jobs:
  build:
    executor: linux-executor
    steps:
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt -y install g++ clang ninja-build cmake zlib1g-dev libzstd-dev libpfm4-dev llvm-18-dev llvm-18-runtime
      - checkout
      - run:
          name: Configure CMake
          command: |
            mkdir build
            cmake -B build -G Ninja
      - run:
          name: Build Project
          command: cmake --build build --config Release -j 4
      - persist_to_workspace:
          root: build
          paths:
            - "*"

  test:
    executor: linux-executor
    steps:
      - attach_workspace:
          at: ~/tau-lang/build
      - run:
          name: Run Tests
          command: ctest --test-dir build --output-on-failure

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
